### ISSUE TITLE
Gnome 42 support?

### ISSUE THREAD

**Issue by Tuxino88** [ExposedCat/snowy#11]
any plan ?

**Comment by ExposedCat** [comment]
@Tuxino88 I'll definitely port extension after G42 release. Now, if you use beta, you can try to add `42` to list of versions in `manifest.json` so if gnome developers did not broke something, it will work as expected

**Comment by Tuxino88** [comment]
mar 23 00:01:35 fedora gnome-shell[22290]: JS ERROR: Extension snowy@exposedcat: TypeError: Config is not a constructor
                                           enable@/home/hellgate/.local/share/gnome-shell/extensions/snowy@exposedcat/extension.js:12:20
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:181:32
                                           _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:507:35
                                           _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:507:14
                                           createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
                                           enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:208:29
                                           EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:447:38
                                           _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:310:38
                                           _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
mar 23 00:01:35 fedora gnome-shell[22290]: Some code accessed the property 'Config' on the module 'config'. That property was defined with 'let' or 'const' inside the mo>
mar 23 00:01:35 fedora gnome-shell[22290]: Some code accessed the property 'Manager' on the module 'manager'. That property was defined with 'let' or 'const' inside the >
mar 23 00:01:35 fedora gnome-shell[22290]: Some code accessed the property 'Snowflake' on the module 'snowflake'. That property was defined with 'let' or 'const' inside >
mar 23 00:01:34 fedora com.github.rafo[22956]

**Comment by psydvl** [comment]
Also, look for gnome 43
Already on my openSUSE Tumbleweed)

**Comment by ExposedCat** [comment]
@psydvl I've just updated to the latest beta Fedora & GNOME and now I'm able to test it in real environment. Thank you for the reminder

**Comment by psydvl** [comment]
Winter is coming...
