### ISSUE TITLE
id is not defined

### ISSUE THREAD

**Issue by Marseel-E** [ExposedCat/snowy#12]
I'm on the latest Fedora & Gnome, I just found the extension on [gnome.extensions.org](https://gnome.extensions.org) and tried to use it but I'm getting this error.

![Screenshot from 2022-11-17 20-39-38](https://user-images.githubusercontent.com/74118311/202597023-566f6661-cd05-4783-adb7-bfac2b97b851.png)

**Comment by ExposedCat** [comment]
@Marseel-E Thank you for your report. By some reason GNOME extension API became weird since 42 version, and I can't even see that changes in docs. Really strange 🤔

**Comment by ExposedCat** [comment]
Fixed
