### ISSUE TITLE
Keyboard shortcut feature request

### ISSUE THREAD

**Issue by kerozoli** [ExposedCat/snowy#14]
Could you please add a keyboard shortcut (maybe configurable) to be able to easily turn off/on the snow :) ?

**Comment by ExposedCat** [comment]
@kerozoli thanks for your suggestion. Actually, you can use `gnome-extensions` utility with GNOME settings to achieve so. Just go to `Settings` - `Keyboard` - `View and customize shortcuts` - `Custom shortcuts` - `Add`. Then add two shortcuts for enabling and disabling extension. The commands are, to enable:
```bash
gnome-extensions enable snowy@exposedcat
```
to disable:

```bash
gnome-extensions disable snowy@exposedcat
```
Here is how it should look like
![image](https://user-images.githubusercontent.com/44642024/209474013-635bb454-a128-4f06-ae41-97b8a7f0a2e2.png)
