### ISSUE TITLE
Cannot find settings

### ISSUE THREAD

**Issue by joezhouchenye** [ExposedCat/snowy#19]
GNOME 42.9. No GUI for 42 I understand. However, where is the gsettings optioin?

**Comment by ExposedCat** [comment]
@joezhouchenye GUI settings are only in G45

G42 is pretty outdated but you should be able to access settings via CLI (see https://github.com/ExposedCat/snowy/tree/v1.3.0#configuration)

**Comment by joezhouchenye** [comment]
Thanks, it works. I am still using Ubuntu 22.04 LTS.
