### ISSUE TITLE
Turning off broke extension

### ISSUE THREAD

**Issue by psydvl** [ExposedCat/snowy#2]
When I'm turning off this extension, it keeps being active and 'Extensions' app shows error:
`Argument tag: value is out of range for uint32` 
(same in Looking Glass (aka <kbd>Alt</kbd>+<kbd>F2</kbd>+`lg`))
![image](https://user-images.githubusercontent.com/43755002/146646479-4eea6aab-ce32-47ca-87ec-b6ae1b8f25aa.png)
logs showing next:
```
JS ERROR: Extension snowy@exposedcat: Error: Argument tag: value is out of range for uint32
disable@/run/current-system/sw/share/gnome-shell/extensions/snowy@exposedcat/extension.js:91:25
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:107:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:498:45
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:498:24
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:528:46
disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:208:29
DisableExtension@resource:///org/gnome/shell/ui/shellDBus.js:423:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:310:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
```

Running on NixOS 21.11, GNOME Shell 41.1

**Comment by ExposedCat** [comment]
@psydvl thank you for taking time to write this report, it is very important for the extension development. Bug fix is on [review](https://extensions.gnome.org/review/28540) now. Until it's not accepted you can replace `~/.local/share/gnome-shell/extensions/snowy@exposedcat` with source code from `main` branch of this repo.
