### ISSUE TITLE
Gnome shell crashes if interval between falling is set to 0

### ISSUE THREAD

**Issue by FelixFourcolor** [ExposedCat/snowy#20]
I was messing around and curious what would happen if I set interval between falling to 0. No surprises, gnome shell crashes. It crashes every time gnome shell is started, effectively breaking gnome shell altogether.

Suggestion: Prevent users from setting that value to 0.

------------

I also need help. 😅 I was able to log in to the tty and manually remove the extension, therefore save my gnome installation. But I still want to use the extension (no more messing around this time). If I reinstall it, the previous setting will be applied, and gnome will crash again.

How do I change the extension config? Is the config file stored somewhere? (I don't see it in `~/.config`.)

**Comment by ExposedCat** [comment]
@FelixFourcolor Thanks for the report, will fix that. As for the reset, you can access settings via CLI: https://github.com/ExposedCat/snowy/tree/v1.3.0#configuration

**Comment by ExposedCat** [comment]
@FelixFourcolor thank you once again for the report, issue is fixed on `main` and will be available on Gnome Extensions within the next release. Minimum fall interval is now 1s (1000ms)
