### ISSUE TITLE
Gnome 47 error

### ISSUE THREAD

**Issue by cortegaunam** [ExposedCat/snowy#23]
If I install the extension from source code it works fine but automatically report an update for the next login.

When I log out and then log in again the extension was automatically updated but isn't working.

Typing Fn + F2 + lg I can see the next error on the extension 

![imagen](https://github.com/user-attachments/assets/d714a327-d6d2-462d-b7be-cd6e93a88f48)

The same problem if I install the extension from extensions.gnome.org

**Comment by ExposedCat** [comment]
Thank you for the report! I re-opened #21 which is the same issue
