### ISSUE TITLE
Manager.js

### ISSUE THREAD

**Issue by PennyJim** [ExposedCat/snowy#6]
In the current version of the extension (and main), there is a bug in the manager script:
In the for loop, your condition is checking the index against a constant of flakes it needs to currently create `i < snowFlakesCount` and the number of flakes it currently needs to create against the config value `snowFlakesCount <= config.int('flakes-limit')`
I assume what you want for the latter is instead the current total of flakes against the config value `this.snowFlakesCount <= config.int('flakes-limit')`

I would recommend renaming the constant to newFlakes, or something like that, to avoid any further confusion. `const newFlakes = random(config.int('min-flakes'), config.int('max-flakes'))`

**Comment by ExposedCat** [comment]
@PennyJim, thanks for reporting this: such reports are essential and really useful for the development of the extension. You are absolutely right, I'll fix this bug.
