### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by PennyJim** [ExposedCat/snowy#7]
- [x] Make the fall parameters configurable (min and max fall duration)
- [x] Make the rotation of the snowflakes random (and their min and max configurable)
- [ ] Add a boolean to the config that'll toggle whether or not the size (linearly) correlates to fall speed

I would fork and attempt to add these via pull requests, but I really don't know what I'm doing with github and I'm unaware of the impact of config so I'm wary to use it all that often.
On the note of optimization I would think (but I am by no means confident) that most things involving the config could be passed using the constructor of the snowflake. At least the splitting of the flake-icons string should probably done once, but it's not currently running slow so idk.

**Comment by PennyJim** [comment]
I attempted to do the first two on my own, and while I have no clue what I'm breaking (It's not even erroring, just not snowing) I've succeeded in making the snowflakes fall to the left *and* right by changing the `rotation_angle_z` to `random(1, 2) % 2 == 1 ? -30 : 30`.

**Comment by ExposedCat** [comment]
@PennyJim Thanks for your suggestions, each one is great.
I will fix "every-time-gsettings-calling" only after adding GUI for setting, since for now it's necessary for auto-applying after changing gsettings value.
> I attempted to do the first two on my own

Can I see your code? I can't find fork in your repos, is it private?

**Comment by PennyJim** [comment]
> Can I see your code? I can't find fork in your repos, is it private?
I did not fork it. I just jammed my hand into the extension files and fiddled with them. I will work on attempting to fork it right now to both learn how to and share what I attempted.

**Comment by ExposedCat** [comment]
@PennyJim after forking, just make changes in your new forked repo. When you'll be done, start pull request to this repo.
Btw now I see it.

**Comment by PennyJim** [comment]
I think I've done it with #9?
